# nixpacks.toml

[phases.setup]
# Definisikan semua paket yang kita butuhkan secara manual.
# Ini akan menginstal PHP 8.1, Apache, Composer, dan library klien MySQL.
nixPkgs = [
  "pkgs.php81",
  "pkgs.apacheHttpd",
  "pkgs.composer",
  "pkgs.libmysqlclient"
]