# nixpacks.toml

# Gunakan provider PHP versi 8.1
[providers]
php = "8.1"

# Modifikasi paket Nix yang diinstal
[phases.setup.nixPkgs]
# Hapus Nginx dari paket default untuk menghindari tabrakan
remove = ["nginx"]
# Tambahkan Apache sebagai server web
add = ["pkgs.apacheHttpd"]