# nixpacks.toml

# 1. Definisikan provider sebagai sebuah array (sequence)
providers = ["php"]

# 2. Atur versi PHP melalui environment variable
[variables]
NIXPACKS_PHP_VERSION = "8.1"

# 3. Modifikasi paket Nix yang akan diinstal
[phases.setup.nixPkgs]
# Tambahkan Apache sebagai server web
add = ["pkgs.apacheHttpd"]
# Hapus Nginx dari paket default untuk menghindari tabrakan
remove = ["nginx"]