# nixpacks.toml

# Definisikan provider sebagai sebuah array (sequence)
providers = ["php"]

# Tambahkan paket Apache di fase setup
[phases.setup]
nixPkgs = ["pkgs.apacheHttpd"]

# Atur versi PHP menggunakan variabel khusus Nixpacks
[variables]
NIXPACKS_PHP_VERSION = "8.1"