[variables]
NIXPACKS_PROVIDER = 'php'

[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']

[phases.build]
cmds = [
    'cd AUTOCARE || echo "Directory AUTOCARE not found"',
    'composer install --no-dev --optimize-autoloader 2>/dev/null || echo "No composer.json found, skipping composer install"'
]

[phases.start]
cmd = 'cd AUTOCARE && php -S 0.0.0.0:$PORT -t .'